version: '3.8'

# Settings and configurations that are common for all contairners
x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9001" /data
  ports:
      - ${MINIO_PUBLIC_PORT}:9000
      - ${MINIO_PRIVATE_PORT}:9001
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

x-postgis-common: &postgis-common
  image: kartoza/postgis:${POSTGRES_MAJOR_VERSION}-${POSTGIS_MAJOR_VERSION}.${POSTGIS_MINOR_RELEASE}
  restart: on-failure
  environment: 
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASS=${POSTGRES_PASSWORD}
    - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
    - POSTGRES_MULTIPLE_EXTENSIONS=${POSTGRES_MULTIPLE_EXTENSIONS}
    - RUN_AS_ROOT=true
  ports:
    - ${POSTGIS_PUBLIC_PORT}:5432
  healthcheck:
    test: "PGPASSWORD=${POSTGRES_PASSWORD} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
    interval: 1m30s
    timeout: 10s
    retries: 3
    start_period: 1m
    
x-pgadmin-common: &pgadmin-common
  image: dpage/pgadmin4:latest
  restart: always
  environment:
    - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  volumes:
    - ./pgadmin:/var/lib/pgadmin
  ports:
    - ${PGADMIN_PUBLIC_PORT}:8888

x-geoserver-common: &geoserver-common
  image: kartoza/geoserver:${GS_VERSION}
  ports:
    - ${GEOSERVER_PORT}:8080
  restart: on-failure
  environment:
    - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
    - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
    - INITIAL_MEMORY=${INITIAL_MEMORY}
    - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
    - STABLE_EXTENSIONS=${STABLE_EXTENSIONS}
    - COMMUNITY_EXTENSIONS=${COMMUNITY_EXTENSIONS}
    - GEOSERVER_CONTEXT_ROOT=${GEOSERVER_CONTEXT_ROOT}
    - ROOT_WEBAPP_REDIRECT=true
    - CONSOLE_HANDLER_LEVEL=${CONSOLE_HANDLER_LEVEL}
  healthcheck:
    test: [ "CMD-SHELL", "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u $${GEOSERVER_ADMIN_USER}:$${GEOSERVER_ADMIN_PASSWORD} http://localhost:${GEOSERVER_PORT}/geoserver/rest/about/version.xml" ]
    interval: 1m30s
    timeout: 10s
    retries: 3
    start_period: 1m
# All services
services: 
  minio:
    <<: *minio-common
    hostname: minio
    container_name: minio
    volumes: 
      - ./s3:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - hoangth33
  db:
    <<: *postgis-common
    hostname: db
    container_name: db
    volumes:
      - ./postgis:/var/lib/postgresql
      - ./dbbackups:/backups
    networks:
      - hoangth33
  pgadmin:
    <<: *pgadmin-common
    hostname: pgadmin
    container_name: pgadmin
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hoangth33
  geoserver:
    <<: *geoserver-common
    hostname: geoserver
    container_name: geoserver
    volumes:
      - ./geoserver:/opt/geoserver/data_dir
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hoangth33
networks:
  hoangth33:
    driver: bridge