version: '3.9'
services: 
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes: 
      - ./storage:/data
    environment:
      - MINIO_ROOT_USER: hoangth33
      - MINIO_ROOT_PASSWORD: Huyhoang6669@
    command: server --console-address ":9001" /data
    networks:
      - hoangth33
networks:
  hoangth33:
    driver: bridge